---
# role: ansible-role-skeleton
# file: .travis.yml

language: python

python:
  - "3.9"

services: docker

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install -r requirements.txt

script:
  - ansible --version
  - molecule --version
